# Generated by Django 2.0.4 on 2018-05-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, verbose_name='LOGIN')),
                ('senha', models.CharField(max_length=20, verbose_name='SENHA')),
                ('nome', models.CharField(max_length=50, verbose_name='NOME')),
                ('email', models.CharField(max_length=90, verbose_name='EMAIL')),
                ('celular', models.CharField(max_length=12, verbose_name='CELULAR')),
                ('dataExpiracao', models.DateField(verbose_name='DATAEXPIRACAO')),
            ],
        ),
    ]
