# Generated by Django 2.0.4 on 2018-05-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=2000, verbose_name='TITULO')),
                ('descricao', models.CharField(max_length=2000, verbose_name='DESCRICAO')),
                ('conteudo', models.CharField(max_length=2000, verbose_name='CONTEUDO')),
                ('tipo', models.CharField(max_length=2000, verbose_name='TIPO')),
                ('extra', models.CharField(max_length=2000, verbose_name='EXTRA')),
                ('idProfessor', models.IntegerField(max_length=2000, verbose_name='ID_PROFESSOR')),
            ],
        ),
    ]
