# Generated by Django 2.0.4 on 2018-05-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB_lms', '0003_auto_20180501_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='idProfessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Professor'),
        ),
    ]
