# Generated by Django 2.0.4 on 2018-05-01 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB_lms', '0004_auto_20180501_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadevinculada',
            name='id_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Atividade'),
        ),
        migrations.AlterField(
            model_name='atividadevinculada',
            name='id_disciplinaOfertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.DisciplinaOfertada'),
        ),
        migrations.AlterField(
            model_name='atividadevinculada',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Professor'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='id_coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Coordenador'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Professor'),
        ),
        migrations.AlterField(
            model_name='disciplinaofertada',
            name='id_coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Coordenador'),
        ),
        migrations.AlterField(
            model_name='disciplinaofertada',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Curso'),
        ),
        migrations.AlterField(
            model_name='disciplinaofertada',
            name='id_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplinaofertada',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Professor'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='id_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Aluno'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='id_atividade_vinculada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.AtividadeVinculada'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Professor'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='id_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Aluno'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Professor'),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='id_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Aluno'),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='id_coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.Coordenador'),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='id_disciplinaOfertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DB_lms.DisciplinaOfertada'),
        ),
    ]
